public with sharing class loginpage 
{

        public String str { get; set; }

   
        public String Password {get; set;}
        public String Username { get; set; }
        
        public loginpage()
        {
        }
        
        public PageReference cancel()
         {
        return null;
        }
        public PageReference save()
         {
        return null;
            }
             public PageReference Register() 
             {
            return null;
               }


    
    }