public with sharing class Sample {

    public String str { get; set; }

    public String cities { get; set; }

    public String city { get; set; }

    public String check3 { get; set; }

    public String check2 { get; set; }

    public String check1 { get; set; }

    public Sample() {

    }


    public Sample(ApexPages.StandardController controller) {

    }


    public String data { get; set; }
}